### ISSUE TITLE
File "/home/sa/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 175, in load_model_from_hdf5     raise ValueError('No model found in config file.') ValueError: No model found in config file.

### ISSUE THREAD

**Issue by APeiZou** [vietanhdev/tf-blazepose#15]
When I load the h5 model file, the code reports an error.
File "/home/sa/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 175, in load_model_from_hdf5
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

**Comment by devvikas** [comment]
are you passing the correct path of h5 file in the config file at line # 33 in the pretrained_weights_path
