### ISSUE TITLE
request for pre-trained weights

### ISSUE THREAD

**Issue by mukeshnarendran7** [vietanhdev/tf-blazepose#20]
If you have the pre-trained weights for this model trained on mpii datset to share would be nice to have them for testing use. Thanks

**Comment by SamySorial99** [comment]
Did you find any pre-trained weightes?
if so can you send them to me please?

**Comment by mukeshnarendran7** [comment]
Hey [SamySorial99](https://github.com/SamySorial99), I didn't come across MPII weights. There are only weights for the hand pose estimation model on this repository
